coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

ignore:
  - "src/index.ts"               # CLI orchestration
  - "src/ui.ts"                  # Console output formatting
  - "src/config.ts"              # Simple env var loading
  - "src/commoncrawl/index.ts"   # HTTP fetch wrapper
  - "src/commoncrawl/cdx-index.ts"  # Subprocess streaming (parseCdxLine tested separately)
  - "src/storage/local.ts"       # File system operations
  - "src/storage/r2.ts"          # S3/R2 operations
